[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["ChainCoopSaving", "ChainCoopManagement", "YieldErc20_BreadToken"]
[rpc_endpoints]
lisk = "${LISK_RPC_URL}"



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
